# Generated by Django 3.2.13 on 2022-11-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='movie_title',
        ),
    ]
