# Generated by Django 3.2.13 on 2022-11-22 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='user_id',
            new_name='user',
        ),
    ]
