# Generated by Django 3.2.13 on 2022-11-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_remove_journal_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='movie_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
