# Generated by Django 3.2.13 on 2022-11-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('journals', '0003_journal_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='movie_title',
        ),
        migrations.AddField(
            model_name='journal',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie'),
            preserve_default=False,
        ),
    ]
