# Generated by Django 3.2.13 on 2022-11-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddfield',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_%Y/%m/%d/'),
        ),
    ]
