# Generated by Django 3.2.13 on 2022-11-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='poster_path',
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_image',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
