# Generated by Django 3.2.13 on 2022-11-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comment_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='journal_image',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='like_users',
        ),
    ]
