# Generated by Django 3.2.13 on 2022-11-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221121_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='user_id',
            new_name='user',
        ),
    ]
